import manga_logo from './project_profiles/manga-logo.png'
import pland_logo from './project_profiles/plantd-logo.png'
import reuters_logo from './project_profiles/reuters-logo.png'
const projects=[ 
    {
      id: 1,
      logo:reuters_logo,
      name: "Reuters - RCOM",
      currentSprint: "Sprint-4",
      startDate: "2022-03-01",
      endDate: "2022-09-31",
      issues: 16,
      backlogs: 24,
      scrum_master: "Blake Cohen",
      overall_sprint_prog: {
        time_elapsed: "49%",
        work_completed: "53%",
        scope_change: "0%",
        blocker: 1,
        flagged: 1,
      },
      stories_status: {
        backlog: 9,
        dev_in_progress: 5,
        completed: 3,
      },
      velocity: "velocity",
      risk: true,
    },{
        id: 2,
        logo: manga_logo,
        name: "SRMG - Manga PH3",
        currentSprint: "Sprint-3",
        startDate: "2022-03-01",
        endDate: "2022-09-30",
        issues: 16,
        backlogs: 24,
        scrum_master: "Milton Wade",
        overall_sprint_prog: {
          time_elapsed: "55%",
          work_completed: "70%",
          scope_change: "0%",
          blocker: 0,
          flagged: 1,
        },
        stories_status: {
          backlog: 9,
          dev_in_progress: 5,
          completed: 3,
        },
        velocity: "velocity",
        risk: false,
      },
    {
      id: 3,
      logo: pland_logo,
      name: "PlanetD - Mobile App",
      currentSprint: "Sprint-5",
      startDate: "2022-01-26",
      endDate: "2022-03-26",
      issues: 14,
      backlogs: 12,
      scrum_master: "Jesse Saunders",
      overall_sprint_prog: {
        time_elapsed: "50%",
        work_completed: "40%",
        scope_change: "0%",
        blocker: 2,
        flagged: 1,
      },
      stories_status: {
        backlog: 8,
        dev_in_progress: 4,
        completed: 4,
      },
      velocity: "velocity",
      risk: false,
    },
    {
      id: 4,
      logo: reuters_logo,
      name: "Reuters - Emerald",
      currentSprint: "Sprint-5",
      startDate: "2022-01-26",
      endDate: "2023-03-26",
      issues: 16,
      backlogs: 24,
      scrum_master: "Jeremiah Owens",
      overall_sprint_prog: {
        time_elapsed: "60%",
        work_completed: "45%",
        scope_change: "0%",
        blocker: 2,
        flagged: 1,
      },
      stories_status: {
        backlog: 9,
        dev_in_progress: 8,
        completed: 9,
      },
      velocity: "velocity",
      risk: false,
    },
  ]
export default projects